name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-analysis:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven  # Enable automatic Maven dependency caching

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -Pbuild org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=YacineAll_newsapi-java-client

      - name: OWASP Dependency Check
        run: mvn verify dependency-check:check -Pbuild

      - name: Run tests and collect coverage
        run: mvn -B test -Pbuild

      - name: Mutation Testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage -Pbuild

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
